# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Build settings
markdown: "kramdown"
repository: "ISSOtm/issotm.github.io"
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-redirect-from
include: ["_pages"]

collections:
  projects:
    output: true
  pokexploits:
    output: true
  fools2019:
    output: true


# Site settings
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://eldred.fr"
locale: "en-US"
google_site_verification: "ljmYhpaVJNaCEk64aV0NyYzauKGSEUtOS2nsYEx7JD0"
title: "ISSOtm's warehouse"
description: "Eldred's personal website, potentially including lots of programming and nerdery. Especially geared towards Game Boy stuff."


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
